# Generated by Django 4.2.3 on 2023-07-22 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wechat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LargeClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('delete', models.BooleanField(default=False, help_text='假删除标志')),
                ('class_name', models.CharField(help_text='大类名称', max_length=64, verbose_name='大类名称')),
                ('description', models.TextField(blank=True, help_text='说明', null=True, verbose_name='说明')),
            ],
            options={
                'verbose_name_plural': '大类目',
                'db_table_comment': '大类目',
            },
        ),
        migrations.CreateModel(
            name='SubClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('delete', models.BooleanField(default=False, help_text='假删除标志')),
                ('class_name', models.CharField(help_text='小类名称', max_length=64, verbose_name='小类名称')),
                ('description', models.TextField(blank=True, help_text='说明', null=True, verbose_name='说明')),
                ('large_class', models.ForeignKey(help_text='大类目', on_delete=django.db.models.deletion.CASCADE, to='tiku.largeclass', verbose_name='大类目')),
            ],
            options={
                'verbose_name_plural': '小类目',
                'db_table_comment': '小类目',
            },
        ),
        migrations.CreateModel(
            name='TestPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('delete', models.BooleanField(default=False, help_text='假删除标志')),
                ('paper_name', models.CharField(help_text='测试名称', max_length=128, verbose_name='测试名称')),
                ('description', models.TextField(blank=True, help_text='说明', null=True, verbose_name='说明')),
            ],
            options={
                'verbose_name_plural': '测试试卷',
                'db_table_comment': '测试试卷',
            },
        ),
        migrations.CreateModel(
            name='SurveyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('delete', models.BooleanField(default=False, help_text='假删除标志')),
                ('openid', models.CharField(help_text='小程序中的openid', max_length=128)),
                ('phone', models.CharField(help_text='用户手机号', max_length=11, verbose_name='手机号')),
                ('completed', models.BooleanField(default=False, verbose_name='是否完成答题')),
                ('test_paper', models.ForeignKey(help_text='测试试卷', on_delete=django.db.models.deletion.CASCADE, to='tiku.testpaper', verbose_name='测试试卷')),
                ('user', models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.DO_NOTHING, to='wechat.user', verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '答题卡',
                'db_table_comment': '答题卡',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('delete', models.BooleanField(default=False, help_text='假删除标志')),
                ('order', models.IntegerField(help_text='题目序号', verbose_name='序号')),
                ('topic', models.TextField(help_text='题目', verbose_name='题目')),
                ('a_ans', models.CharField(default='A.根本不是这样', help_text='A选项', max_length=128, verbose_name='A选项')),
                ('a_score', models.IntegerField(blank=True, default=1, null=True, verbose_name='A选项分数')),
                ('b_ans', models.CharField(default='B.这不太像我', help_text='B选项', max_length=128, verbose_name='B选项')),
                ('b_score', models.IntegerField(blank=True, default=2, null=True, verbose_name='B选项分数')),
                ('c_ans', models.CharField(default='C.我不好说', help_text='C选项', max_length=128, verbose_name='C选项')),
                ('c_score', models.IntegerField(blank=True, default=3, null=True, verbose_name='C选项分数')),
                ('d_ans', models.CharField(default='D.这比较像我', help_text='D选项', max_length=128, verbose_name='D选项')),
                ('d_score', models.IntegerField(blank=True, default=4, null=True, verbose_name='D选项分数')),
                ('e_ans', models.CharField(default='E.我就是这样', help_text='E选项', max_length=128, verbose_name='E选项')),
                ('e_score', models.IntegerField(blank=True, default=5, null=True, verbose_name='E选项分数')),
                ('large_class', models.ForeignKey(help_text='大类目', on_delete=django.db.models.deletion.CASCADE, to='tiku.largeclass', verbose_name='所属大类')),
                ('sub_class', models.ForeignKey(help_text='小类目', on_delete=django.db.models.deletion.CASCADE, to='tiku.subclass', verbose_name='所属小类')),
                ('test_paper', models.ForeignKey(help_text='测试试卷', on_delete=django.db.models.deletion.CASCADE, to='tiku.testpaper', verbose_name='测试试卷')),
            ],
            options={
                'verbose_name_plural': '题目',
                'db_table_comment': '题目',
            },
        ),
        migrations.CreateModel(
            name='ScoreInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('delete', models.BooleanField(default=False, help_text='假删除标志')),
                ('min_score', models.IntegerField(default=0, help_text='最小值', verbose_name='最小值分数')),
                ('max_score', models.IntegerField(default=100, help_text='最大值', verbose_name='最大值分数')),
                ('description', models.TextField(blank=True, help_text='说明', null=True, verbose_name='说明')),
                ('sub_class', models.ForeignKey(help_text='小类目', on_delete=django.db.models.deletion.CASCADE, to='tiku.subclass', verbose_name='小类目')),
            ],
            options={
                'verbose_name_plural': '小类分数区间',
                'db_table_comment': '分数区间',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('delete', models.BooleanField(default=False, help_text='假删除标志')),
                ('opt', models.CharField(blank=True, choices=[('a_ans', 'A'), ('b_ans', 'B'), ('c_ans', 'C'), ('d_ans', 'D'), ('e_ans', 'E')], max_length=8, null=True, verbose_name='当前选项')),
                ('opt_score', models.IntegerField(blank=True, default=0, null=True, verbose_name='选项分数')),
                ('servey_result', models.ForeignKey(help_text='问卷ID', on_delete=django.db.models.deletion.CASCADE, to='tiku.surveyresult', verbose_name='调查结果')),
                ('subject', models.ForeignKey(help_text='题目', on_delete=django.db.models.deletion.CASCADE, to='tiku.subject', verbose_name='题目')),
            ],
            options={
                'verbose_name_plural': '选项',
                'db_table_comment': '用户选项',
            },
        ),
        migrations.AddField(
            model_name='largeclass',
            name='test_paper',
            field=models.ForeignKey(help_text='测试试卷', on_delete=django.db.models.deletion.CASCADE, to='tiku.testpaper', verbose_name='测试试卷'),
        ),
    ]
