# Generated by Django 4.2.3 on 2023-07-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiku', '0004_alter_surveyresult_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='opt',
            field=models.CharField(blank=True, choices=[('a_ans', 'A'), ('b_ans', 'B'), ('c_ans', 'C'), ('d_ans', 'D'), ('e_ans', 'E')], default='', max_length=8, null=True, verbose_name='当前选项'),
        ),
        migrations.AlterField(
            model_name='scoreinterval',
            name='max_score',
            field=models.IntegerField(default=100, help_text='score < 最大值', verbose_name='最大值分数'),
        ),
        migrations.AlterField(
            model_name='scoreinterval',
            name='min_score',
            field=models.IntegerField(default=0, help_text='最小值 <= score', verbose_name='最小值分数'),
        ),
    ]
