# Generated by Django 4.2.3 on 2023-07-25 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiku', '0006_alter_option_options_alter_subject_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LargeScoreInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('delete', models.BooleanField(default=False, help_text='假删除标志')),
                ('min_score', models.IntegerField(default=0, help_text='最小值 <= score', verbose_name='最小值分数')),
                ('max_score', models.IntegerField(default=100, help_text='score < 最大值', verbose_name='最大值分数')),
                ('grade', models.CharField(blank=True, default='', help_text='评级', max_length=32, null=True, verbose_name='评级')),
                ('description', models.TextField(blank=True, help_text='说明', null=True, verbose_name='说明')),
            ],
            options={
                'verbose_name_plural': '分数区间-大类',
                'db_table_comment': '分数区间-大类',
            },
        ),
        migrations.CreateModel(
            name='SubScoreInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('delete', models.BooleanField(default=False, help_text='假删除标志')),
                ('min_score', models.IntegerField(default=0, help_text='最小值 <= score', verbose_name='最小值分数')),
                ('max_score', models.IntegerField(default=100, help_text='score < 最大值', verbose_name='最大值分数')),
                ('grade', models.CharField(blank=True, default='', help_text='评级', max_length=32, null=True, verbose_name='评级')),
                ('description', models.TextField(blank=True, help_text='说明', null=True, verbose_name='说明')),
            ],
            options={
                'verbose_name_plural': '分数区间-小类',
                'db_table_comment': '分数区间-小类',
            },
        ),
        migrations.CreateModel(
            name='TotalScoreInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('delete', models.BooleanField(default=False, help_text='假删除标志')),
                ('min_score', models.IntegerField(default=0, help_text='最小值 <= score', verbose_name='最小值分数')),
                ('max_score', models.IntegerField(default=1000, help_text='score < 最大值', verbose_name='最大值分数')),
                ('grade', models.CharField(blank=True, default='', help_text='评级', max_length=32, null=True, verbose_name='评级')),
                ('description', models.TextField(blank=True, help_text='说明', null=True, verbose_name='说明')),
            ],
            options={
                'verbose_name_plural': '分数区间-总分',
                'db_table_comment': '分数区间-总分',
            },
        ),
        migrations.AddField(
            model_name='largeclass',
            name='total_score',
            field=models.IntegerField(blank=True, default=100, null=True, verbose_name='大类总分数'),
        ),
        migrations.AddField(
            model_name='subclass',
            name='total_score',
            field=models.IntegerField(blank=True, default=100, null=True, verbose_name='小类总分数'),
        ),
        migrations.AddField(
            model_name='testpaper',
            name='total_score',
            field=models.IntegerField(blank=True, default=1000, null=True, verbose_name='测试总分数'),
        ),
        migrations.DeleteModel(
            name='ScoreInterval',
        ),
        migrations.AddField(
            model_name='totalscoreinterval',
            name='test_paper',
            field=models.ForeignKey(help_text='测试试卷', on_delete=django.db.models.deletion.CASCADE, to='tiku.testpaper', verbose_name='测试试卷'),
        ),
        migrations.AddField(
            model_name='subscoreinterval',
            name='sub_class',
            field=models.ForeignKey(help_text='小类目', on_delete=django.db.models.deletion.CASCADE, to='tiku.subclass', verbose_name='小类目'),
        ),
        migrations.AddField(
            model_name='largescoreinterval',
            name='large_class',
            field=models.ForeignKey(help_text='小类目', on_delete=django.db.models.deletion.CASCADE, to='tiku.largeclass', verbose_name='小类目'),
        ),
    ]
