# Generated by Django 4.2.3 on 2023-07-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiku', '0007_largescoreinterval_subscoreinterval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='largeclass',
            name='description',
            field=models.TextField(blank=True, default='', help_text='说明', null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='largescoreinterval',
            name='description',
            field=models.TextField(blank=True, default='', help_text='说明', null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='subclass',
            name='description',
            field=models.TextField(blank=True, default='', help_text='说明', null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='subscoreinterval',
            name='description',
            field=models.TextField(blank=True, default='', help_text='说明', null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='surveyresult',
            name='results_json',
            field=models.JSONField(blank=True, default=dict, help_text='分数统计的结果', null=True, verbose_name='问卷结果'),
        ),
        migrations.AlterField(
            model_name='surveyresult',
            name='school_level',
            field=models.CharField(blank=True, choices=[('LQB', '清北'), ('L985', '985'), ('L211', '211'), ('LONE', '一本'), ('LTWO', '二本以下')], default='LQB', max_length=4, null=True, verbose_name='预估院校档次'),
        ),
        migrations.AlterField(
            model_name='testpaper',
            name='description',
            field=models.TextField(blank=True, default='', help_text='说明', null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='totalscoreinterval',
            name='description',
            field=models.TextField(blank=True, default='', help_text='说明', null=True, verbose_name='说明'),
        ),
    ]
