# Generated by Django 4.2.3 on 2023-07-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiku', '0008_alter_largeclass_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpaper',
            name='spend_time',
            field=models.IntegerField(blank=True, default=120, null=True, verbose_name='预计花费时间(s)'),
        ),
    ]
