# Generated by Django 4.2.3 on 2023-07-30 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiku', '0009_testpaper_spend_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='largescoreinterval',
            name='large_class',
            field=models.ForeignKey(help_text='小类目', on_delete=django.db.models.deletion.CASCADE, to='tiku.largeclass', verbose_name='大类目'),
        ),
    ]
