# Generated by Django 4.2.3 on 2023-08-03 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0004_alter_user_age_alter_user_grade_alter_user_name_and_more'),
        ('tiku', '0010_alter_largescoreinterval_large_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresult',
            name='user',
            field=models.ForeignKey(blank=True, help_text='用户', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wechat.user', verbose_name='用户'),
        ),
    ]
