# Generated by Django 4.2.3 on 2023-08-14 17:24

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiku', '0014_remove_testpaper_description_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='largescoreinterval',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', help_text='说明', null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='subscoreinterval',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', help_text='说明', null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='totalscoreinterval',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', help_text='说明', null=True, verbose_name='说明'),
        ),
    ]
