# Generated by Django 4.2.3 on 2023-08-14 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiku', '0016_testpaper_description_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testpaper',
            old_name='description_image',
            new_name='desc_url',
        ),
    ]
