# Generated by Django 4.2.3 on 2023-08-16 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiku', '0017_rename_description_image_testpaper_desc_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyresult',
            options={'ordering': ['-created'], 'verbose_name_plural': '答题卡'},
        ),
    ]
