# Generated by Django 4.2.3 on 2023-08-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiku', '0018_alter_surveyresult_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpaper',
            name='desc_url',
            field=models.URLField(blank=True, default='', help_text='说明图片', null=True, verbose_name='说明图片'),
        ),
    ]
