# Generated by Django 4.2 on 2023-09-01 12:21

import apps.tiku.models
from django.db import migrations, models
import django_oss_storage.backends


class Migration(migrations.Migration):

    dependencies = [
        ('tiku', '0019_alter_testpaper_desc_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpaper',
            name='desc_url',
            field=models.ImageField(blank=True, default='', help_text='说明图片', null=True, storage=django_oss_storage.backends.OssMediaStorage, upload_to=apps.tiku.models.image_upload_to, verbose_name='说明图片'),
        ),
    ]
