# Generated by Django 4.2.3 on 2023-07-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('delete', models.BooleanField(default=False, help_text='假删除标志')),
                ('xetong_address', models.URLField(help_text='小鹅通地址', verbose_name='小鹅通地址')),
            ],
            options={
                'verbose_name_plural': '全局配置',
                'db_table_comment': '全局配置',
            },
        ),
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('delete', models.BooleanField(default=False, help_text='假删除标志')),
                ('title', models.CharField(help_text='标题', max_length=256, verbose_name='标题')),
                ('url', models.URLField(help_text='点击的相关链接', verbose_name='链接')),
                ('image', models.ImageField(help_text='图片地址', upload_to='', verbose_name='图片地址')),
            ],
            options={
                'verbose_name_plural': '课程资讯',
                'db_table_comment': '课程资讯',
            },
        ),
    ]
