# Generated by Django 4.2.3 on 2023-07-24 22:42

import apps.config.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_alter_config_evaluation_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('delete', models.BooleanField(default=False, help_text='假删除标志')),
                ('title', models.CharField(help_text='标题', max_length=256, verbose_name='标题')),
                ('a_type', models.CharField(choices=[('curation', '精选'), ('history', '历史'), ('community', '社区推荐')], help_text='类型', max_length=16, verbose_name='类型')),
                ('description', models.TextField(help_text='描述', verbose_name='描述')),
                ('image', models.ImageField(help_text='文章图片地址', upload_to=apps.config.models.image_upload_to, verbose_name='文章图片地址')),
                ('url', models.URLField(help_text='文章点击的相关链接', verbose_name='链接')),
            ],
            options={
                'verbose_name_plural': '文章管理',
                'db_table_comment': '文章管理',
            },
        ),
        migrations.AlterField(
            model_name='config',
            name='shop_address',
            field=models.URLField(blank=True, default='', help_text='首页右侧商店地址', null=True, verbose_name='逆袭商店地址'),
        ),
        migrations.AlterField(
            model_name='config',
            name='xetong_address',
            field=models.URLField(blank=True, default='', help_text='首页左侧公众号地址', null=True, verbose_name='树成林公众号地址'),
        ),
    ]
