# Generated by Django 4.2.3 on 2023-08-13 16:14

import apps.config.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_article_alter_config_shop_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='shop_address',
            field=models.ImageField(blank=True, default='', help_text='逆袭商店二维码图片地址', null=True, upload_to=apps.config.models.image_upload_to, verbose_name='逆袭商店二维码图片地址'),
        ),
        migrations.AlterField(
            model_name='config',
            name='xetong_address',
            field=models.ImageField(blank=True, default='', help_text='树成林公众号二维码图片地址', null=True, upload_to=apps.config.models.image_upload_to, verbose_name='树成林公众号二维码图片地址'),
        ),
    ]
