# Generated by Django 4.2.3 on 2023-07-22 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('delete', models.BooleanField(default=False, help_text='假删除标志')),
                ('openid', models.CharField(help_text='小程序中的openid', max_length=128, unique=True)),
                ('name', models.CharField(help_text='用户姓名', max_length=16, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('0', '男'), ('1', '女')], max_length=2, verbose_name='性别')),
                ('age', models.IntegerField(help_text='用户年龄', verbose_name='年龄')),
                ('grade', models.CharField(help_text='用户年龄', max_length=32, verbose_name='年级')),
                ('phone', models.CharField(help_text='用户手机号', max_length=11, unique=True, verbose_name='手机号')),
                ('group_number', models.CharField(blank=True, default='', help_text='你所在群的群号（1群请填1，以此类推）', max_length=128, null=True, verbose_name='群号')),
                ('college_score', models.FloatField(blank=True, default=0, help_text='高考预估分数', null=True, verbose_name='预估分数')),
                ('school_level', models.CharField(blank=True, choices=[('LQB', '清北'), ('L985', '985'), ('L211', '211'), ('LONE', '一本'), ('LTWO', '二本以下')], max_length=4, null=True, verbose_name='预估院校档次')),
            ],
            options={
                'verbose_name_plural': '高考用户',
                'db_table_comment': '高考用户',
            },
        ),
    ]
