# Generated by Django 4.2.3 on 2023-07-23 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='college_score',
        ),
        migrations.RemoveField(
            model_name='user',
            name='school_level',
        ),
    ]
