# Generated by Django 4.2.3 on 2023-07-23 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0002_remove_user_college_score_remove_user_school_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group_number',
        ),
    ]
