# Generated by Django 4.2.3 on 2023-07-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0003_remove_user_group_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, default=18, help_text='用户年龄', null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(blank=True, default='', help_text='用户年龄', max_length=32, null=True, verbose_name='年级'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='', help_text='用户姓名', max_length=16, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='用户手机号', max_length=11, null=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('0', '男'), ('1', '女')], default='0', max_length=2, null=True, verbose_name='性别'),
        ),
    ]
